language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
before_install:
  - gem update bundler
script:
  - bundle exec rake
after_script:
  - bundle exec codeclimate-test-reporter
env:
  - CODECLIMATE_REPO_TOKEN=8717c954cb9c11a6720098955568a6a39361a59fa2612d3854800a553af13c4e
